version: '3'
services:
  books-service:
    build:
      context: ./books-service
    depends_on:
      - authors-service
      - categories-service
      - books-db
    ports:
      - 3000:3000
    networks:
      - my_network

  authors-service:
    build:
      context: ./authors-service
    ports:
      - 4000:4000
    depends_on:
      - authors-db
    networks:
      - my_network

  categories-service:
    build:
      context: ./categories-service
    ports:
      - 5000:5000
    depends_on:
      - categories-db
    networks:
      - my_network

  books-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: books
    volumes:
      - ./books.sql:/docker-entrypoint-initdb.d/create-books-db.sql
    networks:
      - my_network

  authors-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: authors
    volumes:
      - ./authors.sql:/docker-entrypoint-initdb.d/create-authors-db.sql
    networks:
      - my_network   

  categories-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: categories
    volumes:
      - ./categories.sql:/docker-entrypoint-initdb.d/create-categories-db.sql
    networks:
      - my_network 
networks:
  my_network: